export const AI_PLAYSTYLES = {
  balanced: {
    label: 'Balanced',
    damageWeight: 1.0,
    blockWeight: 1.0,
    statusWeight: 1.6,
    healWeight: 1.0,
    drawWeight: 1.0,
    ramWeight: 1.0,
    costPenalty: 3.0,
    useCounterPenalty: 10,
    finalMutCounterPenalty: 25,
    posMutBonus: 5,
    negMutPenalty: 3,
    restThreshold: 0.5,
    shopGoldThreshold: 60,
    eliteBonus: 0,
    rewardTypeWeights: { Attack: 5, Power: 14, Skill: 12, Defense: 8, Support: 10, Utility: 8 },
    rewardMutRiskCutoff: null,
    rewardSkipFloor: -18,
    restPriority: ['heal', 'forge', 'stabilise', 'repair'],
    shopGoldReserve: 40,
    shopScrapReserve: 0,
    shopBuyCards: true,
    shopPreferCardTypes: ['Attack', 'Power', 'Skill', 'Defense'],
    shopAvoidCardTypes: [],
    shopBuyHeal: true,
    shopBuyRepair: false,
    shopBuyStabilise: true,
    shopBuyAccelerate: false,
    shopBuyForge: true,
    shopBuyRemoveCard: false,
    shopRemoveTargetTypes: [],
  },
  aggressive: {
    label: 'Aggressive',
    damageWeight: 1.8,
    blockWeight: 0.4,
    statusWeight: 1.9,
    healWeight: 0.3,
    drawWeight: 0.8,
    ramWeight: 0.8,
    costPenalty: 2.0,
    useCounterPenalty: 4,
    finalMutCounterPenalty: 8,
    posMutBonus: 7,
    negMutPenalty: 2,
    restThreshold: 0.25,
    shopGoldThreshold: 80,
    eliteBonus: 35,
    rewardTypeWeights: { Attack: 18, Power: 16, Skill: 8, Defense: -5, Support: -3, Utility: 5 },
    rewardMutRiskCutoff: null,
    rewardSkipFloor: -24,
    restPriority: ['heal'],
    shopGoldReserve: 20,
    shopScrapReserve: 0,
    shopBuyCards: true,
    shopPreferCardTypes: ['Attack', 'Power', 'Skill'],
    shopAvoidCardTypes: ['Defense', 'Support'],
    shopBuyHeal: false,
    shopBuyRepair: false,
    shopBuyStabilise: false,
    shopBuyAccelerate: false,
    shopBuyForge: false,
    shopBuyRemoveCard: true,
    shopRemoveTargetTypes: ['Defense', 'Support'],
  },
  defensive: {
    label: 'Defensive',
    damageWeight: 0.7,
    blockWeight: 2.2,
    statusWeight: 1.7,
    healWeight: 2.0,
    drawWeight: 1.0,
    ramWeight: 1.0,
    costPenalty: 3.5,
    useCounterPenalty: 12,
    finalMutCounterPenalty: 30,
    posMutBonus: 4,
    negMutPenalty: 5,
    restThreshold: 0.7,
    shopGoldThreshold: 50,
    eliteBonus: -25,
    rewardTypeWeights: { Attack: 0, Power: 8, Skill: 14, Defense: 22, Support: 14, Utility: 6 },
    rewardMutRiskCutoff: null,
    rewardSkipFloor: -16,
    restPriority: ['heal', 'forge', 'stabilise', 'repair'],
    shopGoldReserve: 25,
    shopScrapReserve: 0,
    shopBuyCards: true,
    shopPreferCardTypes: ['Defense', 'Skill', 'Support', 'Power'],
    shopAvoidCardTypes: ['Attack'],
    shopBuyHeal: true,
    shopBuyRepair: true,
    shopBuyStabilise: true,
    shopBuyAccelerate: false,
    shopBuyForge: true,
    shopBuyRemoveCard: false,
    shopRemoveTargetTypes: [],
  },
  buffDebuff: {
    label: 'Buff / Debuff',
    damageWeight: 0.8,
    blockWeight: 1.5,
    statusWeight: 2.8,
    healWeight: 1.0,
    drawWeight: 1.3,
    ramWeight: 1.3,
    costPenalty: 2.8,
    useCounterPenalty: 12,
    finalMutCounterPenalty: 28,
    posMutBonus: 9,
    negMutPenalty: 4,
    restThreshold: 0.6,
    shopGoldThreshold: 55,
    eliteBonus: 8,
    rewardTypeWeights: { Attack: -5, Power: 18, Skill: 16, Defense: 10, Support: 12, Utility: 12 },
    rewardMutRiskCutoff: null,
    rewardSkipFloor: -16,
    restPriority: ['stabilise', 'heal', 'forge', 'repair'],
    shopGoldReserve: 25,
    shopScrapReserve: 0,
    shopBuyCards: true,
    shopPreferCardTypes: ['Skill', 'Power', 'Defense', 'Utility', 'Support'],
    shopAvoidCardTypes: ['Attack'],
    shopBuyHeal: true,
    shopBuyRepair: false,
    shopBuyStabilise: true,
    shopBuyAccelerate: false,
    shopBuyForge: true,
    shopBuyRemoveCard: false,
    shopRemoveTargetTypes: [],
  },
  preservation: {
    label: 'Card Preservation',
    damageWeight: 1.0,
    blockWeight: 1.2,
    statusWeight: 1.0,
    healWeight: 1.3,
    drawWeight: 1.0,
    ramWeight: 1.0,
    costPenalty: 3.5,
    useCounterPenalty: 30,
    finalMutCounterPenalty: 60,
    posMutBonus: 5,
    negMutPenalty: 10,
    restThreshold: 0.6,
    shopGoldThreshold: 50,
    eliteBonus: -12,
    rewardTypeWeights: {},
    rewardMutRiskCutoff: 3,
    rewardSkipFloor: 6,
    restPriority: ['forge', 'repair', 'stabilise', 'heal'],
    shopGoldReserve: 20,
    shopScrapReserve: 1,
    shopBuyCards: false,
    shopPreferCardTypes: [],
    shopAvoidCardTypes: [],
    shopBuyHeal: true,
    shopBuyRepair: true,
    shopBuyStabilise: true,
    shopBuyAccelerate: false,
    shopBuyForge: true,
    shopBuyRemoveCard: false,
    shopRemoveTargetTypes: [],
  },
  mutationPusher: {
    label: 'Mutation Pusher',
    damageWeight: 1.2,
    blockWeight: 0.8,
    statusWeight: 1.0,
    healWeight: 0.7,
    drawWeight: 0.9,
    ramWeight: 0.9,
    costPenalty: 2.5,
    useCounterPenalty: -18,
    finalMutCounterPenalty: -25,
    posMutBonus: 8,
    negMutPenalty: 1,
    restThreshold: 0.4,
    shopGoldThreshold: 60,
    eliteBonus: 12,
    rewardTypeWeights: { Attack: 5, Power: 8, Skill: 5, Defense: 0, Support: 5, Utility: 5 },
    rewardMutRiskCutoff: null,
    rewardSkipFloor: -30,
    restPriority: ['heal', 'repair'],
    shopGoldReserve: 25,
    shopScrapReserve: 0,
    shopBuyCards: true,
    shopPreferCardTypes: ['Attack', 'Power', 'Skill'],
    shopAvoidCardTypes: [],
    shopBuyHeal: false,
    shopBuyRepair: false,
    shopBuyStabilise: false,
    shopBuyAccelerate: true,
    shopBuyForge: false,
    shopBuyRemoveCard: false,
    shopRemoveTargetTypes: [],
  },
};

export function getAiPlaystyleLabel(playstyle = 'balanced') {
  return AI_PLAYSTYLES[playstyle]?.label ?? playstyle;
}

export function getAiPlaystyleSlug(playstyle = 'balanced') {
  return getAiPlaystyleLabel(playstyle).replace(/\s+/g, '_');
}
